version: '3'

services:
    zookeeper:
        image: confluentinc/cp-zookeeper
        environment: 
            - ZOOKEEPER_CLIENT_PORT=2181
        ports:
            - "2181:2181"

    kafka:
        image: confluentinc/cp-kafka
        environment: 
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper

    schema-registry:
        image: confluentinc/cp-schema-registry
        environment: 
            - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
            - SCHEMA_REGISTRY_HOST_NAME=schema-registry
            - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
        ports:
            - "8008:8081"
        depends_on:
            - kafka

    kafka-rest:
        image: confluentinc/cp-kafka-rest
        environment: 
            - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_REST_LISTENERS=http://0.0.0.0:8082
            - KAFKA_REST_SCHEMA_REGISTRY_URL=http://schema-registry:8081
            - KAFKA_REST_HOST_NAME=kafka-rest
        ports:
            - "8082:8082"
        depends_on:
            - schema-registry
            
    control-center:
        image: confluentinc/cp-enterprise-control-center
        environment: 
            - CONTROL_CENTER_ZOOKEEPER_CONNECT=zookeeper:2181
            - CONTROL_CENTER_BOOTSTRAP_SERVERS=kafka:9092
            - CONTROL_CENTER_REPLICATION_FACTOR=1 
            - CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS=1
            - CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS=1 
            - CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS=2
            - CONTROL_CENTER_CONNECT_CLUSTER=http://kafka-connect:8082
        ports:
            - "9021:9021"
        depends_on:
            - kafka
            - kafka-rest
        volumes:
            - "/tmp/control-center/data:/var/lib/confluent-control-center"
        ulimits:
            nofile:
                soft: 16384
                hard: 16384

networks:
    default:
        external:
            name: confluent 